testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Leave Management"
    owner: "Sneha Makade"
    lastUpdate: "23 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "All field values of policy details values should display at dashboard after adding policy"
    browsers:
        - "Chromium"
    steps:
        - "Go to HR -> Leave Management -> Policy"
        - "Verify default 'paid leave' policy is present at dashboard"
        - "Add Policy"
        - "Verify added policy is present at dashboard"
        - "Go to Employee -> Leave Management -> Policy"
        - "Verify 'paid leave' policy and added policy are present at dashboard"
        - "Verify type of policy added should get display below leave type field"
        - "Verify leave cycle of policy should get display below leave cycle field"
        - "Verify leaves added for particular policy should get display below no. of leaves field"
        - "Verify accumulate yes or no should get display below accumulate field"
        - "Verify maximum leaves added for particular policy should get display below max leaves field"
        - "Verify encashment yes or no should get display below encashment field"
    conditions:
        - "Test fails if all field values of policy details values do not display at dashboard after adding policy"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "23 June, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 12 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
        