testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Salary TDS"
    owner: "Sneha Makade"
    lastUpdate: "25 May, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Clicked view declaration details popup form should show filled information"
    browsers:
        - "Chrome"
        - "Chromium"
    steps:
        - "Go to EMPLOYEE -> Salary TDS -> Declaration"
        - "Check spelling on all text contents"
        - "Click on 'Add Declaration' button, add declaration popup form should get open"
        - "Fill all the mandatory fields, click on 'Add' button, declaration should get display at dashboard"
        - "Verify status of added declaration should display as pending declaration approval"
        - "Go to 'Finance' tab, click on salary tds, it should show three submenus like declaration, pending declaration approval, pending proof approval"
        - "Click on pending declaration approval, it should show added declaration from employee -> salary tds tab, with view and action icon"
        - "Click on action icon, it should show approve, reject, change request"
        - "Click on approve, approve declaration popup form should get open, add comment in comment input field"
        - "Click on 'Approve' button in approve declaration popup form, popup should get closed, and that declaration should go in declaration dashboard with status declaration approved"
        - "Go to 'Employee' tab, click on salary tds, declaration"
        - "Verify added declarations status now get changed into declaration approved with only view icon"
        - "Click on view icon, declaration details popup form should get open"
        - "Verify added declaration date should display infront of submitted on field"
        - "Verify running year should display infront of financial year field"
        - "Verify description added for declaration should display infront of description field"
        - "Verify added declaration category should display infront of category field"
        - "Verify amount added for declaration should display infront of amount field"
        - "Verify comment added for approving declaration should display infront of comment field"
        conditions:
        - "Test fails if all filled information do not get display in declaration details popup form"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "25 May, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 25 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
        