testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Organization"
    owner: "Sneha Makade"
    lastUpdate: "04 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Org details popup should display all values with correct alignment"
    browsers:
        - "Chrome"
        - "Chromium"
    steps:
        - "Go to AMBERSALES -> Organization"
        - "Check spelling on all text contents"
        - "Click on 'Add org' button, org details popup form should get open"
        - "Fill all the mandatory fields, click on 'Add' button in org details popup form"
        - "Verify organization should get display at dashboard with view and edit icon"
        - "Click on view icon, it should open org details popup"
        - "Verify organization name should get display in front of org name field"
        - "Verify organization url should get display in front of org url field"
        - "Verify organization size should get display in front of org size field"
        - "Verify organization type should get display in front of org type field"
        - "Verify pan no. added should get display in front of pan field"
        - "Verify organization is verified or not should get display in front of org verified field"
        - "Verify description added should get display in front of description field"
        - "Verify address added should get display in front of address field"
        - "Verify name of admin should get display in front of admin name field"
        - "Verify email of admin should get display in front of admin email field"
    conditions:
        - "Test fails if org details popup do not display all entered values with correct alignment"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "04 June, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 10 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
