testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Pending Offer"
    owner: "Sneha Makade"
    lastUpdate: "29 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Candidate not joined popup form should display all values and should move to not joined dashboard"
    browsers:
        - "Chrome"
    steps:
        - "Go to HR -> Pending Offer"
        - "Check spelling on all text contents"
        - "Click on 'Add Offer' button, offer for candidate popup form should get open"
        - "Fill all the mandatory fields, click on 'Add' button in form" 
        - "Verify pending offer should get display at dashboard"
        - "Click on 'Not Joined' icon, candidate not joined popup form should get open"
        - "Verify employee name added in offer for candidate form should get display in name field"
        - "Enter date of not joining in not joining date field"
        - "Click on 'Not Joined' button, candidate not joined popup form should get close"
        - "Go to HR -> Not joined"
        - "Verify not joined employee should get display at not joined dashboard"
    conditions:
        - "Test fails if candidate not joined popup form do not display all values and do not move to not joined dashboard"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "29 June, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 15 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
        