testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Salary TDS"
    owner: "Sneha Makade"
    lastUpdate: "24 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Declaration parameters values should get display at dashboard after approve, reject or change requesting declaration"
    browsers:
        - "Chromium"
    steps:
        - "Go to Employee -> Salary TDS -> Declaration"
        - "Add declaration of different categories"
        - "Go to Finance -> Salary TDS -> Pending Declaration Approval"
        - "Verify added declaration from employee tab is present at pending declaration approval dashboard"
        - "Click on 'Action' icon, select one action from approve, reject, change request"
        - "Verify after approving, rejecting, or change requesting done declaration should get removed from dashboard"
        - "Go to Finance -> Salary TDS -> Declaration"
        - "Verify declaration should get display at dashboard with one of the status as ' declaration approved', 'rejected', 'request change'"
        - "Verify id of employee should get display below id field"
        - "Verify employee name should get display below name input field"
        - "Verify present financial year should get display below financial year field"
        - "Verify date of declaration should get display below submitted on field"
        - "Verify category of added declaration should get display below category field"
        - "Verify amount of declaration should get display below amount field"
        - "Verify status of declaration should get display below status field"
    conditions:
        - "Test fails if declaration parameters values do not get display at dashboard after approve, reject, or change requesting declaration"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "24 June, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 15 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
