testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Customer"
    owner: "Vipul Suryawanshi"
    lastUpdate: "23 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Purchase order pop-up should display all filled values"
    browsers:
        - "Firefox"
    steps:
        - "Go to Finance -> Customer -> PO received"
        - "Verify that the default page is customer 'PO received'"
        - "Verify that left menu customer po received is highlighted"
        - "Check spelling on all text contents"
        - "Click on 'Add Purchase Order' button, add purchase order pop-up should get open"
        - "Fill all mandatory fields"
        - "Click on 'Create Purchase Order' button in add purchase order pop-up"
        - "Verify purchase order should get display at po received"
        - "Click on 'View' icon, purchase order pop-up should get open"
        - "Verify that there is customer name and company name"
        - "Verify that po number should get display"
        - "Verify po date and po due date should get display in front of 'PO date' and 'PO due date' field"
        - "Verify that there are items list(Item Name, Description, Quantity, Price)"
        - "Verify item name and description should get display below 'Item' and 'Description' field"
        - "Verify quantity and price should get display below 'Quantity' and 'Price' field"
        - "Verify amount should get display below 'Amount' field"
        - "Verify total amount should get display in front of 'Total' field"
        - "Click on 'Download' button, purchase order receipt should get download"
    conditions:
        - "Test fails if purchase order pop-up does not display updated values at dashboard"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "23 June, 2020" #set the last when this test was run
    runBy: Vipul suryawanshi #name of the person running this testType
    duration: 15 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
        bugNum: #if bug was reported and filed, report the bug number here