testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Task"
    owner: "Jafar Pathan"
    lastUpdate: "17 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Search filter should work for entered assignee name"
    browsers:
        - "Chrome"
        - "Firefox"
    steps:
        - "Go to MyTeam -> Tasks -> Blocked"
        - "Verify that in search filter it shows placeholder 'Search by name...'"
        - "Click on 'Search by name' filter"
        - "Enter valid name in 'Search by name' field"
        - "If entered name not match with added task assignee name then it shows 'Sorry , no record found for this page'"
        - "If search by name match added task assignee name then shows particular entry on dashboard"
    conditions:
        - "Test fails, if search filter do not work for entered assignee name"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: 17 June, 2020 #set the last when this test was run
    runBy: Jafar pathan #name of the person running this testType
    duration: 05 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
        bugNum: #if bug was reported and filed, report the bug number here
