testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Task"
    owner: "Jafar Pathan"
    lastUpdate: "17 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Blocked task details should show on view pop-up"
    browsers:
        - "Chrome"
        - "Firefox"
    steps:
        - "Go to MyTeam -> Tasks -> Pending"
        - "Click on 'Add task' button"
        - "'Pending Task Details' pop-up should be open"
        - "Fill all required fields and click on 'Add' button"
        - "Verify that task added by manager listed on pending task dashboard"
        - "Click on action icon, select action item 'Block'"
        - "'Block task' pop-up should open with two fields (Blocked On Whom, Reason)"
        - "Fill all required fields and click on 'Block' button"
        - "Go to MyTeam -> Tasks -> Blocked"
        - "Verify that pending task moved to the blocked task dashboard"
        - "Verify that all team members blocked task are listed in blocked task dashboard"
        - "Verify two action icon (view, history) are displayed with blocked task"
        - "Click on view icon, view pop-up should be open with blocked task details"
    conditions:
        - "Test fails if blocked task details not showing on View pop-up"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: 17 June, 2020 #set the last when this test was run
    runBy: Jafar pathan #name of the person running this testType
    duration: 30 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
        bugNum: #if bug was reported and filed, report the bug number here
