testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Leave Management"
    owner: "Sneha Makade"
    lastUpdate: "09 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Apply leaves popup form should display all filled values"
    browsers:
        - "Chromium"
    steps:
        - "Go to HR -> Employee -> Dashboard"
        - "Click on 'Add Employee' button, it should open employee details popup form"
        - "Fill all the mandatory fields, click on 'Next' button in employee details popup form"
        - "Verify employee bank details popup form should get open"
        - "Click on 'Add' button in employee bank details popup form, employee should get added at dashboard"
        - "Go to Leave Management -> Employee"
        - "Click on apply leave icon, it should open apply leaves popup form"
        - "Verify id of employee should get display in front of id field"
        - "Verify name of employee should get display in front of name field"
        - "Verify leave balance of employee should get display in front of leave balance field"
        - "Select leave type in leave type dropdown"
        - "Click on start date, calender should get open, select date"
        - "Enter reason of leave in reason field"
        - "Click on 'Update' button in apply leaves popup form, it should get closed"
        - "Verify total leave balance field should get updated with applied leave"
    conditions:
        - "Test fails if apply leaves popup form do not display all filled values"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "09 June, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 12 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
