testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Expense"
    owner: "Swapnil Sangvikar"
    lastUpdate: "11 june, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Settings field should display all details"
    browsers:
        - "Chrome"
    steps:
        - "Go to EMPLOYEE -> Expense -> Expense Policy"
        - "Verify that the default page is expense policy dashboard"
        - "Verify that left menu expense policy is highlighted"
        - "Check spelling on all text contents"
        - "Verify that in settings 'With Payroll' is present"
        - "Verify that in settings 'No. of cycles' is present"
        - "Verify that in settings data is listed with 'Cycle, Start date, Cutoff date, Payout date'"
    conditions:
        - "Test fails if, settings field should not display all details"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "11 june, 2020" #set the last when this test was run
    runBy: Swapnil Sangvikar #name of the person running this testType
    duration: 15 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
        bugNum: #if bug was reported and filed, report the bug number here

