testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Leave Management"
    owner: "Sneha Makade"
    lastUpdate: "22 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Leave application from employee, mail to manager should contain all the details about employee leave"
    browsers:
        - "Chromium"
    steps:
        - "Login with super admin user"
        - "Go to HR -> Employee -> Dashboard"
        - "Add Employee"
        - "Log in with employee credentials"
        - "Go to Employee -> Leave Management -> My Leaves"
        - "Apply Leave"
        - "Verify 'leave application from tisha' mail sent to mailtrap"
        - "Verify 'From: tisha <mailer@afinpros.com>' this field is present in mails header"
        - "Verify 'To: Anurag Agarwal <anurag@ambersoft.in>' this field is present in mails header"
        - "Verify mails body should contain "Hi Anurag Agarwal, 
          I would like to apply for a leave with following details: 
          Starting Date :	2/6/2020
          Number of Days :	2
          Leave Type :	Paid Leave
          Reason :	hometown going 
          Please approve. 
          Approve
          Reject 
          Regards,
          tisha,
          9876543 
          Powered By aFinPROs.com""
        - "Verify 'approve', 'reject' links are clickable"
    conditions:
        - "Test fails if leave application from employee mail to manager do not contain all details about employee leave"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun: 
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "22 June, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 20 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
        