testType: e2e #Valid types are unit, e2e, load or failure
feature:
    name: "Leave Management"
    owner: "Sneha Makade"
    lastUpdate: "09 June, 2020"
    status: "production" #valid status are "Being defined", "development", "test", "production"
test:
    summary: "Leave calendar details popup form should display all values with correct alignment"
    browsers:
        - "Chromium"
    steps:
        - "Login with super admin user"
        - "Go to HR -> Leave Management -> Calendar"
        - "Click on 'Add Calendar' button, leave calendar details popup form should get open"
        - "Fill all the mandatory fields"
        - "Click on 'Add' button, leave calendar details popup form should get close"
        - "Verify added calendar should get display at dashboard with edit and view icon"
        - "Click on view icon, it should open leave calendar details popup form"
        - "Verify date of leave should get display in front of leave date field"
        - "Verify description added for leave should get display in front of leave description field"
        - "Verify leave is mandatory or not should get display in front of mandatory field"
    conditions:
        - "Test fails if leave calendar details popup form do not display all values with correct alignment"
    automation:
        status: manual #this test is automated or not
        testPath: #set this with a valid path if test is automated
testRun:
    status: pass #valid status are notRun, pass, fail, sometimeFail
    date: "09 June, 2020" #set the last when this test was run
    runBy: Sneha #name of the person running this testType
    duration: 10 seconds #time taken in seconds to run this test
    env: qa #valid value are dev, qa, production
    buildVersion: xxx #mention the build version
    bug:
        details:
                "Multi time bug summary"
        bugNum: #if bug was reported and filed, report the bug number here
        